language: go

go:
  - 1.15.x

os:
  - linux

sudo: false

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install: true

env:
  - GO111MODULE=on

script:
  - go build
  - go test -v -p 1 -parallel 1 -failfast -coverprofile=coverage.txt -covermode=atomic ./...
  - $GOPATH/bin/goveralls -service=travis-ci

