name: Build

on:
  workflow_run:
    workflows: ["Test gosn-v2"]
    types:
      - completed
#  push:
#    branches:
#      - "*"
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Build and Test
        run: |
          go mod tidy
          go test -coverprofile=bin/cov.out -cover -v -failfast -p 1 $(go list ./...)
          go tool cover -func=bin/cov.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SN_SERVER: ${{ secrets.SN_SERVER }}
          SN_EMAIL: ${{ secrets.SN_EMAIL }}
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
