name: Test gosn-v2

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master, main ]
jobs:
  test:
    concurrency:
      group: test
      cancel-in-progress: true
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      -
        name: Tests
        run: |
          go mod tidy
          go test -cover -v -failfast -p 1 $(go list ./...)
        env:
          SN_SERVER: ${{ secrets.SN_SERVER }}
          SN_EMAIL: ${{ secrets.SN_EMAIL }}
          SN_SKIP_SESSION_TESTS: true
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
          SN_SKIP_SESSION_TESTS: true
